# Generated by Django 4.1.5 on 2023-01-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nmaepeople",
            options={"verbose_name": "Имя", "verbose_name_plural": "Имена"},
        ),
        migrations.AddField(
            model_name="nmaepeople",
            name="year",
            field=models.PositiveIntegerField(default=12, verbose_name="Возраст"),
            preserve_default=False,
        ),
    ]
