# Generated by Django 4.1.5 on 2023-01-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_nmaepeople_options_nmaepeople_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nmaepeople",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Имя"),
        ),
    ]
