# Generated by Django 4.1.5 on 2023-01-26 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_rename_nmaepeople_namepeople"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(max_length=255)),
                ("zipcode", models.CharField(max_length=10)),
                ("city", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=2)),
            ],
        ),
        migrations.AlterModelOptions(
            name="namepeople",
            options={"verbose_name": "Имя", "verbose_name_plural": "Имя"},
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "business_addr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="business_addr",
                        to="app.address",
                    ),
                ),
                (
                    "home_addr",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="home_addr",
                        to="app.address",
                    ),
                ),
                (
                    "other_addr",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="other_addr",
                        to="app.address",
                    ),
                ),
            ],
        ),
    ]
