# Generated by Django 4.1.5 on 2023-01-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_address_alter_namepeople_options_person"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name": "Адрес", "verbose_name_plural": "Адреса"},
        ),
        migrations.AlterModelOptions(
            name="person",
            options={"verbose_name": "Человек", "verbose_name_plural": "Человек"},
        ),
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(max_length=255, verbose_name="Город"),
        ),
        migrations.AlterField(
            model_name="address",
            name="state",
            field=models.CharField(max_length=2, verbose_name="Номер"),
        ),
        migrations.AlterField(
            model_name="address",
            name="street",
            field=models.CharField(max_length=255, verbose_name="Адрес"),
        ),
        migrations.AlterField(
            model_name="address",
            name="zipcode",
            field=models.CharField(max_length=10, verbose_name="Индекс"),
        ),
    ]
