# Generated by Django 4.1.5 on 2023-01-26 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_address_options_alter_person_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NamePeople",
        ),
        migrations.RemoveField(
            model_name="person",
            name="other_addr",
        ),
        migrations.AlterField(
            model_name="person",
            name="business_addr",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="business_addr",
                to="app.address",
                verbose_name="Рабочий адрес",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="home_addr",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="home_addr",
                to="app.address",
                verbose_name="Городской адрес",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Информация"),
        ),
    ]
